name: Build and Test Mojo OSS

on:
  pull_request:

jobs:
  test-pre-submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Get the modular installer, install mojo compiler"
        shell: bash
        run: |
          echo "Downloading the Latest Mojo Compiler"
          curl https://get.modular.com | sh - && modular auth buildAndTestMojoOSS
          modular install mojo
          BASHRC=$( [ -f "$HOME/.bash_profile" ] && echo "$HOME/.bash_profile" || echo "$HOME/.bashrc" )
          echo 'export MODULAR_HOME="/home/runner/.modular"' >> "$BASHRC"
          echo 'export PATH="/home/runner/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> "$BASHRC"
          source "$BASHRC"
          mojo --version